<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '978-0-7432-7356-5',
                'publisher' => 'Scribner',
                'year_published' => 1925,
                'pages' => 180,
                'category' => 'Classic Literature',
                'description' => 'A classic American novel set in the Jazz Age about the mysterious millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan.',
                'stock' => 5,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '978-0-06-112008-4',
                'publisher' => 'J.B. Lippincott & Co.',
                'year_published' => 1960,
                'pages' => 376,
                'category' => 'Classic Literature',
                'description' => 'A powerful story of racial injustice and childhood innocence in the American South.',
                'stock' => 3,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'isbn' => '978-0-262-03384-8',
                'publisher' => 'MIT Press',
                'year_published' => 2009,
                'pages' => 1292,
                'category' => 'Computer Science',
                'description' => 'Comprehensive introduction to algorithms and data structures, widely used in computer science education.',
                'stock' => 7,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'isbn' => '978-0-13-235088-4',
                'publisher' => 'Prentice Hall',
                'year_published' => 2008,
                'pages' => 464,
                'category' => 'Software Engineering',
                'description' => 'A handbook of agile software craftsmanship that teaches how to write clean, maintainable code.',
                'stock' => 4,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Design of Everyday Things',
                'author' => 'Don Norman',
                'isbn' => '978-0-465-05065-9',
                'publisher' => 'Basic Books',
                'year_published' => 2013,
                'pages' => 368,
                'category' => 'Design',
                'description' => 'A powerful primer on how design serves as the communication between object and user.',
                'stock' => 2,
                'status' => 'borrowed',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'isbn' => '978-0-06-231609-7',
                'publisher' => 'Harper',
                'year_published' => 2015,
                'pages' => 443,
                'category' => 'History',
                'description' => 'A narrative of humanity\'s creation and evolution, exploring how we organized ourselves in cities, states, and kingdoms.',
                'stock' => 6,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'David Thomas',
                'isbn' => '978-0-201-61622-4',
                'publisher' => 'Addison-Wesley',
                'year_published' => 1999,
                'pages' => 352,
                'category' => 'Software Engineering',
                'description' => 'A practical guide to software development that examines the core process of writing maintainable code.',
                'stock' => 3,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'isbn' => '978-0-7352-1129-2',
                'publisher' => 'Avery',
                'year_published' => 2018,
                'pages' => 320,
                'category' => 'Self-Help',
                'description' => 'A comprehensive guide to breaking bad habits and building good ones through small changes.',
                'stock' => 4,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'isbn' => '978-0-374-27563-1',
                'publisher' => 'Farrar, Straus and Giroux',
                'year_published' => 2011,
                'pages' => 499,
                'category' => 'Psychology',
                'description' => 'A groundbreaking exploration of the two systems that drive the way we think and make decisions.',
                'stock' => 5,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Power of Now',
                'author' => 'Eckhart Tolle',
                'isbn' => '978-1-57731-152-2',
                'publisher' => 'New World Library',
                'year_published' => 1997,
                'pages' => 236,
                'category' => 'Spirituality',
                'description' => 'A guide to spiritual enlightenment through living in the present moment.',
                'stock' => 1,
                'status' => 'maintenance',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'JavaScript: The Good Parts',
                'author' => 'Douglas Crockford',
                'isbn' => '978-0-596-51774-8',
                'publisher' => 'O\'Reilly Media',
                'year_published' => 2008,
                'pages' => 176,
                'category' => 'Programming',
                'description' => 'A concise guide to JavaScript that focuses on the language\'s most useful features.',
                'stock' => 8,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Eloquent JavaScript',
                'author' => 'Marijn Haverbeke',
                'isbn' => '978-1-59327-584-6',
                'publisher' => 'No Starch Press',
                'year_published' => 2014,
                'pages' => 472,
                'category' => 'Programming',
                'description' => 'A modern introduction to programming using JavaScript, covering both the language and web development.',
                'stock' => 6,
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]
        ];

        $this->db->table('books')->insertBatch($data);
    }
}
